import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import subsetFont from 'subset-font'

const root = resolve(import.meta.dirname, '..')
const manifestPath = resolve(root, 'src/components/business/icon-manifest.json')
const glyphsPath = resolve(root, 'src/components/business/icon-glyphs.ts')
const fontPath = resolve(root, 'src/static/icons/tms-icons.ttf')
const sourceCssPath = resolve(root, 'node_modules/bootstrap-icons/font/bootstrap-icons.css')
const sourceFontPath = resolve(root, 'node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff2')

const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
const css = await readFile(sourceCssPath, 'utf8')
const iconCodes = new Map(
  [...css.matchAll(/\.bi-([\w-]+)::before\s*\{\s*content:\s*"\\([0-9a-f]+)";/g)].map(
    ([, name, code]) => [name, Number.parseInt(code, 16)]
  )
)

const glyphs = Object.fromEntries(
  Object.entries(manifest).map(([name, source]) => {
    const codepoint = iconCodes.get(source)
    if (!codepoint) throw new Error(`Unknown Bootstrap icon: ${source} (${name})`)
    return [name, codepoint]
  })
)

const usedCharacters = [...new Set(Object.values(glyphs))]
  .map((codepoint) => String.fromCodePoint(codepoint))
  .join('')
const sourceFont = await readFile(sourceFontPath)
const subset = await subsetFont(sourceFont, usedCharacters, { targetFormat: 'sfnt' })

if (subset.byteLength >= 40 * 1024) {
  throw new Error(`Icon font must stay below the Uni-app local font inlining limit: ${subset.byteLength} bytes`)
}

const lines = [
  '// Generated by pnpm icons:build from icon-manifest.json and Bootstrap Icons.',
  'export const iconGlyphs = {',
  ...Object.entries(glyphs).map(
    ([name, codepoint]) => `  '${name}': '\\u${codepoint.toString(16).padStart(4, '0')}',`
  ),
  '} as const',
  '',
  'export type TmsIconName = keyof typeof iconGlyphs',
  '',
]

await writeFile(fontPath, subset)
await writeFile(glyphsPath, lines.join('\n'))
console.log(`Built ${usedCharacters.length} icons, ${subset.byteLength} byte font`)
